# PostgreSQL. Versions 8.2 and up are supported.
#


development:
  adapter: postgresql
  encoding: unicode
  database: SerenaVaccari_development
  pool: 5
  username: develop
  password: develop

test:
  adapter: postgresql
  encoding: unicode
  database: SerenaVaccari_test
  pool: 5
  username: test
  password: test

production:
  adapter: postgresql
  encoding: unicode
  database: SerenaVaccari_production
  pool: 5
  username: fedetaglia
  password:
